CreditCards/CreditCards/Models/ErrorViewModel.cs
using System;

namespace CreditCards.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CreditCards/CreditCards/ViewModels/NewCreditCardApplicationDetails.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CreditCards.ViewModels
{
    public class NewCreditCardApplicationDetails
    {
        [Display(Name = "First Name")]
        [Required(ErrorMessage = "Please provide a first name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Please provide a last name")]
        public string LastName{ get; set; }

        [Display(Name = "Frequent Flyer Number")]
        [Required(ErrorMessage = "Please provide a frequent flyer number")]
        public string FrequentFlyerNumber { get; set; }

        [Display(Name = "Age (in years)")]
        [Required(ErrorMessage = "Please provide an age in years")]
        [Range(18,int.MaxValue, ErrorMessage = "You must be at least 18 years old")]
        public int? Age { get; set; }

        [Display(Name = "Gross Income")]
        [Required(ErrorMessage = "Please provide your gross income")]        
        public decimal? GrossAnnualIncome { get; set; }

        [Display(Name = "Relationship Status")]
        [Required(ErrorMessage = "Please choose a relationship status")]
        public string RelationshipStatus { get; set; }

        [Display(Name = "How did you hear about us?")]
        [Required(ErrorMessage = "Please select how you heard about us?")]
        public string BusinessSource { get; set; }

        [Display(Name = "Accept terms")]        
        [TrueRequired(ErrorMessage = "You must accept the terms and conditions to continue")]
        public bool TermsAccepted { get; set; }
    }
}

CreditCards/CreditCards/ViewModels/TrueRequiredAttribute.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CreditCards.ViewModels
{
    internal sealed class TrueRequiredAttribute : ValidationAttribute
    {
        public override bool IsValid(object value)
        {            
            if (value is null)
            {
                return false;
            }

            if (value.GetType() != typeof(bool))
            {
                throw new InvalidOperationException("This validation can only be performed on boolean values.");
            }

            return (bool)value;
        }
    }
}

CreditCards/CreditCards/Controllers/ApplyController.cs
using System.Threading.Tasks;
using CreditCards.Core.Interfaces;
using CreditCards.Core.Model;
using CreditCards.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CreditCards.Controllers
{
    public class ApplyController : Controller
    {
        private readonly ICreditCardApplicationRepository _applicationRepository;

        public ApplyController(ICreditCardApplicationRepository applicationRepository)
        {
            _applicationRepository = applicationRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(NewCreditCardApplicationDetails applicationDetails)
        {
            if (!ModelState.IsValid)
            {
                return View(applicationDetails);
            }

            var creditCardApplication = new CreditCardApplication
            {
                FirstName = applicationDetails.FirstName,
                LastName = applicationDetails.LastName,
                FrequentFlyerNumber = applicationDetails.FrequentFlyerNumber,
                Age = applicationDetails.Age.Value,
                GrossAnnualIncome = applicationDetails.GrossAnnualIncome.Value,
                RelationshipStatus = applicationDetails.RelationshipStatus,
                BusinessSource = applicationDetails.BusinessSource
            };
            

            // There is no front-end validation required on the frequent flyer number.
            // If it is invalid the decision will be referred to a human.
            // This is so we don't miss out on potential sales due to people thinking 
            // there frequent flyer number should be valid when it is not.
            var evaluator = new CreditCardApplicationEvaluator(new FrequentFlyerNumberValidator());
            CreditCardApplicationDecision decision = evaluator.Evaluate(creditCardApplication);
            creditCardApplication.Decision = decision;

            await _applicationRepository.AddAsync(creditCardApplication);

            return View("ApplicationComplete", creditCardApplication);
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

CreditCards/CreditCards/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CreditCards.Controllers
{
    public class HomeController : Controller
    {
        [ResponseCache(NoStore = true)]
        public IActionResult Index()
        {
            string[] randomGreetings = { "Hi", "Hey", "Yo" };

            int rndGreetingIndex = new Random().Next(0, randomGreetings.Length);

            ViewData["RandomGreeting"] = randomGreetings[rndGreetingIndex];

            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Demo application for Pluralsight course.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

CreditCards/CreditCards/Controllers/ValuesController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;

namespace CreditCards.Controllers
{
    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new[] { "value1", "value2" };
        }

        [HttpGet("{id}")]
        public IActionResult Get(int id)
        {
            if (id < 1)
            {
                return BadRequest($"Invalid request for id {id}");
            }

            return Content($"Value {id}");
        }

        [HttpPost("StartJob")]
        public IActionResult StartJob()
        {
            return Ok("Batch Job Started");
        }
    }
}

CreditCards/CreditCards/Views/Apply/ApplicationComplete.cshtml
@model CreditCards.Core.Model.CreditCardApplication

@{
    ViewData["Title"] = "Application Complete";
}

<h2>Application Complete</h2>
<div class="row">
    <div class="col-md-3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Application Details
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <p>Application Decision</p>
                </div>
                <div class="panel-body" id="Decision">
                    @Model.Decision
                </div>
                <div class="panel-heading">
                    <p>Application Reference Number</p>
                </div>
                <div class="panel-body" id="ReferenceNumber">
                    @Model.Id
                </div>

                <div class="panel-heading">
                    <p>Name</p>
                </div>
                <div class="panel-body" id="FullName">
                    @Model.FirstName @Model.LastName
                </div>

                <div class="panel-heading">
                    <p>Age</p>
                </div>
                <div class="panel-body" id="Age">
                    @Model.Age
                </div>

                <div class="panel-heading">
                    <p>Gross Annual Income</p>
                </div>
                <div class="panel-body" id="Income">
                    @Model.GrossAnnualIncome
                </div>

                <div class="panel-heading">
                    <p>Relationship Status</p>
                </div>
                <div class="panel-body" id="RelationshipStatus">
                    @Model.RelationshipStatus
                </div>

                <div class="panel-heading">
                    <p>Source Of Business</p>
                </div>
                <div class="panel-body" id="BusinessSource">
                    @Model.BusinessSource
                </div>
            </div>
        </div>
    </div>
</div>

CreditCards/CreditCards/Views/Apply/Index.cshtml
@model CreditCards.ViewModels.NewCreditCardApplicationDetails

@{
    ViewData["Title"] = "Credit Card Application";
}

<h2>New Credit Card Application</h2>
<div class="row">
    <div class="col-md-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Application Details
            </div>
            <div class="panel-body">
                @Html.ValidationSummary()
                <form method="post" asp-controller="Apply" asp-action="Index">
                    <div class="row">
                        <div class="col-md-6">
                            <fieldset class="form-group">
                                <label asp-for="FirstName"></label>
                                <input asp-for="FirstName" class="form-control" />
                            </fieldset>
                            <fieldset class="form-group">
                                <label asp-for="LastName"></label>
                                <input asp-for="LastName" class="form-control" />
                            </fieldset>
                            <fieldset class="form-group">
                                <label asp-for="FrequentFlyerNumber"></label>
                                <input asp-for="FrequentFlyerNumber" class="form-control" />
                            </fieldset>
                            <fieldset class="form-group">
                                <label asp-for="Age"></label>
                                <input asp-for="Age" class="form-control" />
                            </fieldset>
                        </div>
                        <div class="col-md-6">
                            <fieldset class="form-group">
                                <label asp-for="GrossAnnualIncome"></label>
                                <input asp-for="GrossAnnualIncome" class="form-control" />
                            </fieldset>
                            <fieldset class="form-group">
                                <label asp-for="RelationshipStatus"></label>
                                <div class="radio">
                                    <label class="radio-inline"><input id="Married" asp-for="RelationshipStatus" value="Married" type="radio" />Married</label>
                                </div>
                                <div class="radio">
                                    <label class="radio-inline"><input id="Defacto" asp-for="RelationshipStatus" value="De-facto" type="radio" />De facto</label>
                                </div>
                                <div class="radio">
                                    <label class="radio-inline"><input id="Single" asp-for="RelationshipStatus" value="Single" type="radio" />Single</label>
                                </div>
                            </fieldset>
                            <fieldset class="form-group">
                                <label asp-for="BusinessSource"></label>
                                <select asp-for="BusinessSource" class="form-control">
                                    <option value="Declined To Comment">I'd Rather Not Say</option>
                                    <option value="Internet">Internet Search</option>
                                    <option value="Email">Marketing Email</option>
                                    <option value="Word of Mouth">Word of Mouth</option>
                                    <option value="TV">TV Ad</option>
                                </select>
                            </fieldset>
                            <fieldset class="form-check">
                                <input asp-for="TermsAccepted" class="form-check-input" />
                                <label asp-for="TermsAccepted" class="form-check-label"></label>
                            </fieldset>
                            <input id="SubmitApplication" type="submit" value="Submit Application" class="btn btn-primary" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

CreditCards/CreditCards/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

CreditCards/CreditCards/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CreditCards/CreditCards/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Http;

@{
    ViewData["Title"] = "Home Page";
}

@{
    if (Context.Request.Cookies["acceptedCookies"] == null)
    {
        <div>
            <p id="CookiesBeingUsed">This site uses cookies, etc.</p>
        </div>
    }
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="10000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    New low rate
                    <a name="ApplyLowRate" class="btn btn-default" asp-area="" asp-controller="Apply" asp-action="Index">Apply Now!</a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Easy application process
                    <a class="btn btn-default" asp-area="" asp-controller="Apply" asp-action="Index">Easy: Apply Now!</a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Award winning customer service
                    <a class="btn btn-default customer-service-apply-now" asp-area="" asp-controller="Apply" asp-action="Index">Apply Now!</a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<div>
    <table>
        <caption>Product Rates</caption>
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Rate</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Easy Credit Card</td>
                <td>20% APR</td>
            </tr>
            <tr>
                <td>Silver Credit Card</td>
                <td>18% APR</td>
            </tr>
            <tr>
                <td>Gold Credit Card</td>
                <td>17% APR</td>
            </tr>
        </tbody>
    </table>
</div>
<div>
    <div>
        <p>Quick links: <a asp-area="" asp-controller="Apply" asp-action="Index">@ViewData["RandomGreeting"] - Apply Now!</a></p>
    </div>
</div>
<div>
    <a id="LiveChat" href="#" onclick="setTimeout(function() { alert('Live chat is currently closed.'); }, 2000)">Start Live Chat</a>
</div>
<div>
    <a id="LearnAboutUs" href="#" onclick="if (window.confirm('Do you want to learn more about us?')) { window.open('/Home/About','_self') }">Learn more about us</a>
</div>

<hr />
<footer>
    <p>&copy; 2020 - CreditCards</p>
    <p>Time Generated: @DateTime.Now.ToLongTimeString()</p>
    <p id="GenerationToken">@Guid.NewGuid()</p>
    <a id="ContactFooter" target="_blank" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
</footer>

CreditCards/CreditCards/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Credit Cards</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CreditCards</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>